version: 2
jobs:
  build:
    docker:
      - image: aa8y/sbt:1.0
    working_directory: /usr/src/app
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-
      - run: sbt test:compile
      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: sbt test
