version: 2
jobs:
  build:
    docker:
      - image: aa8y/core:gradle5
    working_directory: /usr/src/app
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - gradle-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      # Compile, run checkstyle and tests
      - run: gradle check
