version: 2
jobs:
  build:
    docker:
      - image: aa8y/sbt:ci
    working_directory: /usr/src/app
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - scala-deps-{{ checksum "scala/build.sbt" }}
      - run: cd scala && sbt test:compile
      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.m2
          key: scala-deps--{{ checksum "scala/build.sbt" }}
      - run: cd scala && sbt test
