version: 2
jobs:
  build:
    docker:
      - image: aa8y/core:node11
    working_directory: /usr/src/app
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - npm-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: npm-dependencies-{{ checksum "package.json" }}
      - run: npm test
